# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: talic
description: Hochmodernes Atomic Gaming- & Streaming-OS (KDE Plasma + NVIDIA).

base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 43

modules:
  # Deine eigenen Dateien (Icon etc.) - Das klappt jetzt!
  - type: files
    files:
      - source: usr
        destination: /usr

  # System-Pakete (Mit fest eingetragenen Repos für Fedora 43)
  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm
    install:
      - steam
      - lutris
      - mangohud
      - gamemode
      - obs-studio
      - obs-studio-plugin-vaapi
      - pipewire-utils
      - nvtop
      - btop
      - xorg-x11-drv-nvidia-cuda

  # Das Flatpak-Format (V2)
  - type: default-flatpaks
    configurations:
      - install:
          - org.mozilla.firefox
          - com.discordapp.Discord
          - org.kde.kcalc
          - net.davidotek.pupgui2

  # Scripte (Optimierungen beim Bauen)
  - type: script
    scripts:
      - post-install.sh
